services:
  # The Backend
  backend:
    build:
      context: ./healthsentinel-backend
      dockerfile: Dockerfile
    container_name: hs-backend
    environment:
      - PORT=8000
      - CORS_ORIGINS=http://localhost:3000
    ports:
      - "8000:8000"
    networks:
      - healthsentinel-network

  # The Frontend
  frontend:
    build:
      context: ./healthsentinel-frontend
      dockerfile: Dockerfile
    container_name: hs-frontend
    environment:
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000/ws/patients
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - healthsentinel-network

networks:
  healthsentinel-network:
    driver: bridge
