apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthsentinel-frontend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthsentinel-frontend
  template:
    metadata:
      labels:
        app: healthsentinel-frontend
    spec:
      containers:
      - name: frontend
        image: 856021349334.dkr.ecr.eu-west-3.amazonaws.com/healthsentinel-frontend:latest
        ports:
        - containerPort: 3000
        # --- ADD THIS BLOCK TO CONNECT TO THE BACKEND ---
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://a7e5615e53b9d409dbd857c5f7bbbc33-1309895825.eu-west-3.elb.amazonaws.com"
        # ------------------------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: healthsentinel-frontend-svc
  namespace: default
spec:
  selector:
    app: healthsentinel-frontend
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer
